"""
TeamBench paper-ready table generation.

Merges ablation data from multiple JSON files, computes per-task and
per-category TNI, and generates LaTeX tables for the paper.

Tables produced:
  - Table 2: Per-task ablation results (Oracle, Restricted, Full, TNI, etc.)
  - Table 3: Per-category aggregated results
  - Table 4: Component contribution analysis (Planning, Verification value)

Usage:
    python -m harness.paper_tables \
        --ablation shared/ablation_5task.json shared/ablation_10task.json \
        --output-dir shared/paper/
"""
from __future__ import annotations

import argparse
import json
import math
import os
from collections import defaultdict
from dataclasses import dataclass, field

from harness.compute_tni import TaskMetrics, compute_from_results_json, to_json


# Category prefix -> display name (matches benchmark_stats.py)
CATEGORY_MAP = {
    "SEC": "Security",
    "INC": "Incident Response",
    "CR": "Code Review",
    "SPEC": "Specification",
    "PIPE": "Pipeline",
    "INT": "Integration",
    "O": "Operations",
    "D": "Data Engineering",
    "SQL": "Data Engineering",
    "S": "Software Eng.",
    "GO": "Software Eng.",
    "JS": "Software Eng.",
    "LH": "Long-Horizon",
    "SCALE": "Long-Horizon",
    "SYNTH": "Long-Horizon",
    "P": "Policy",
    "NEG": "Negotiation",
    "MULTI": "Multi-language",
    "TEST": "Testing",
    "IR": "Information Retrieval",
}


def _task_category(task_id: str) -> str:
    """Extract category from task_id like SEC2_auth_bypass -> Security."""
    prefix = ""
    first_part = task_id.split("_")[0] if "_" in task_id else task_id
    for ch in first_part:
        if ch.isalpha():
            prefix += ch
        else:
            break
    return CATEGORY_MAP.get(prefix.upper(), prefix.upper())


def merge_ablation_files(paths: list[str]) -> list[dict]:
    """Merge runs from multiple ablation JSON files, deduplicating by (task, condition, seed)."""
    seen = set()
    merged = []
    for path in paths:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        for run in data.get("runs", []):
            key = (run["task_id"], run["condition"], run.get("seed", 0))
            if key not in seen:
                seen.add(key)
                merged.append(run)
    return merged


def runs_to_task_metrics(runs: list[dict]) -> list[TaskMetrics]:
    """Convert merged runs to per-task TaskMetrics."""
    task_cond: dict[str, dict[str, list[float]]] = defaultdict(lambda: defaultdict(list))
    for run in runs:
        task_id = run["task_id"]
        condition = run["condition"]
        partial = run.get("partial_score", 1.0 if run.get("pass") else 0.0)
        task_cond[task_id][condition].append(float(partial))

    results = []
    for task_id in sorted(task_cond):
        scores = task_cond[task_id]

        def avg(lst: list[float]) -> float:
            return sum(lst) / len(lst) if lst else 0.0

        m = TaskMetrics(
            task_id=task_id,
            oracle_partial=avg(scores.get("oracle", [])),
            restricted_partial=avg(scores.get("restricted", [])),
            team_partial=avg(scores.get("full", [])),
            no_plan_partial=avg(scores.get("team_no_plan", [])),
            no_verify_partial=avg(scores.get("team_no_verify", [])),
        )
        results.append(m)
    return results


def generate_table2(metrics: list[TaskMetrics]) -> str:
    """Generate LaTeX Table 2: Per-task ablation results."""
    lines = [
        "% Auto-generated by harness.paper_tables",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Per-task ablation results with Gemini 2.5 Flash. "
        "Partial scores (0--1) measure graded task completion. "
        "TNI measures the fraction of the oracle--restricted gap recovered by teamwork.}",
        "\\label{tab:ablation-results}",
        "\\small",
        "\\begin{tabular}{llcccccccr}",
        "\\toprule",
        "Task & Category & Oracle & Restricted & Full & No-Plan & No-Verify "
        "& TNI & Plan.V & Ver.V \\\\",
        "\\midrule",
    ]

    for m in sorted(metrics, key=lambda x: _task_category(x.task_id)):
        cat = _task_category(m.task_id)
        # Only show TNI when necessity gap is meaningful (>0.05)
        if not math.isnan(m.tni) and abs(m.necessity_gap) > 0.05:
            tni_s = f"{max(-2.0, min(2.0, m.tni)):.2f}"
        else:
            tni_s = "--"
        pv = f"{m.planning_value:+.2f}" if not math.isnan(m.planning_value) else "--"
        vv = f"{m.verification_value:+.2f}" if not math.isnan(m.verification_value) else "--"

        # Highlight best condition per task
        scores = [
            ("oracle", m.oracle_partial),
            ("restricted", m.restricted_partial),
            ("full", m.team_partial),
        ]
        best = max(scores, key=lambda x: x[1])[0]

        def _fmt(val: float, name: str) -> str:
            s = f"{val:.2f}"
            return f"\\textbf{{{s}}}" if name == best else s

        task_short = m.task_id.replace("_", "\\_")
        lines.append(
            f"{task_short} & {cat} & "
            f"{_fmt(m.oracle_partial, 'oracle')} & "
            f"{_fmt(m.restricted_partial, 'restricted')} & "
            f"{_fmt(m.team_partial, 'full')} & "
            f"{m.no_plan_partial:.2f} & {m.no_verify_partial:.2f} & "
            f"{tni_s} & {pv} & {vv} \\\\"
        )

    # Aggregate row (only include TNI where gap is meaningful)
    valid_tni = [
        max(-2.0, min(2.0, m.tni))
        for m in metrics
        if not math.isnan(m.tni) and abs(m.necessity_gap) > 0.05
    ]
    avg_oracle = sum(m.oracle_partial for m in metrics) / max(1, len(metrics))
    avg_restricted = sum(m.restricted_partial for m in metrics) / max(1, len(metrics))
    avg_full = sum(m.team_partial for m in metrics) / max(1, len(metrics))
    avg_no_plan = sum(m.no_plan_partial for m in metrics) / max(1, len(metrics))
    avg_no_verify = sum(m.no_verify_partial for m in metrics) / max(1, len(metrics))
    avg_tni = sum(valid_tni) / len(valid_tni) if valid_tni else float("nan")
    avg_pv = avg_full - avg_no_plan
    avg_vv = avg_full - avg_no_verify

    tni_s = f"{avg_tni:.2f}" if not math.isnan(avg_tni) else "--"
    lines.extend([
        "\\midrule",
        f"\\textbf{{Average}} & ({len(metrics)} tasks) & "
        f"{avg_oracle:.2f} & {avg_restricted:.2f} & {avg_full:.2f} & "
        f"{avg_no_plan:.2f} & {avg_no_verify:.2f} & "
        f"{tni_s} & {avg_pv:+.2f} & {avg_vv:+.2f} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table*}",
    ])

    return "\n".join(lines)


def generate_table3(metrics: list[TaskMetrics]) -> str:
    """Generate LaTeX Table 3: Per-category aggregated ablation results."""
    cat_metrics: dict[str, list[TaskMetrics]] = defaultdict(list)
    for m in metrics:
        cat = _task_category(m.task_id)
        cat_metrics[cat].append(m)

    lines = [
        "% Auto-generated by harness.paper_tables",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Per-category ablation summary. "
        "Team Uplift = Full $-$ Restricted. "
        "Planning Value = Full $-$ No-Plan.}",
        "\\label{tab:category-ablation}",
        "\\small",
        "\\begin{tabular}{lrccccc}",
        "\\toprule",
        "Category & $n$ & Oracle & Restricted & Full & Uplift & Plan.V \\\\",
        "\\midrule",
    ]

    total_n = 0
    total_oracle = 0.0
    total_restricted = 0.0
    total_full = 0.0

    for cat in sorted(cat_metrics):
        ms = cat_metrics[cat]
        n = len(ms)
        total_n += n
        avg_o = sum(m.oracle_partial for m in ms) / n
        avg_r = sum(m.restricted_partial for m in ms) / n
        avg_f = sum(m.team_partial for m in ms) / n
        avg_np = sum(m.no_plan_partial for m in ms) / n
        uplift = avg_f - avg_r
        pv = avg_f - avg_np

        total_oracle += avg_o * n
        total_restricted += avg_r * n
        total_full += avg_f * n

        lines.append(
            f"{cat} & {n} & {avg_o:.2f} & {avg_r:.2f} & "
            f"{avg_f:.2f} & {uplift:+.2f} & {pv:+.2f} \\\\"
        )

    # Overall
    if total_n > 0:
        o_avg = total_oracle / total_n
        r_avg = total_restricted / total_n
        f_avg = total_full / total_n
        lines.extend([
            "\\midrule",
            f"\\textbf{{Overall}} & {total_n} & {o_avg:.2f} & {r_avg:.2f} & "
            f"{f_avg:.2f} & {f_avg - r_avg:+.2f} & -- \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
        ])

    return "\n".join(lines)


def generate_table4(metrics: list[TaskMetrics]) -> str:
    """Generate LaTeX Table 4: Component contribution analysis."""
    lines = [
        "% Auto-generated by harness.paper_tables",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Component contribution analysis. "
        "Planning Value measures the impact of the Planner role. "
        "Verification Value measures the impact of the Verifier role. "
        "Tasks where team outperforms oracle indicate that role separation "
        "and remediation loops provide complementary benefits.}",
        "\\label{tab:component-contribution}",
        "\\small",
        "\\begin{tabular}{lcccl}",
        "\\toprule",
        "Task & Plan. Value & Verif. Value & Team $>$ Oracle? & Classification \\\\",
        "\\midrule",
    ]

    for m in sorted(metrics, key=lambda x: -(x.planning_value if not math.isnan(x.planning_value) else 0)):
        pv = f"{m.planning_value:+.2f}" if not math.isnan(m.planning_value) else "--"
        vv = f"{m.verification_value:+.2f}" if not math.isnan(m.verification_value) else "--"
        team_gt_oracle = "\\cmark" if m.team_partial > m.oracle_partial + 0.01 else ""
        task_short = m.task_id.replace("_", "\\_")
        lines.append(
            f"{task_short} & {pv} & {vv} & {team_gt_oracle} & {m.classification} \\\\"
        )

    # Aggregate
    valid_pv = [m.planning_value for m in metrics if not math.isnan(m.planning_value)]
    valid_vv = [m.verification_value for m in metrics if not math.isnan(m.verification_value)]
    team_wins = sum(1 for m in metrics if m.team_partial > m.oracle_partial + 0.01)

    avg_pv = sum(valid_pv) / len(valid_pv) if valid_pv else 0
    avg_vv = sum(valid_vv) / len(valid_vv) if valid_vv else 0

    lines.extend([
        "\\midrule",
        f"\\textbf{{Average}} & {avg_pv:+.2f} & {avg_vv:+.2f} & "
        f"{team_wins}/{len(metrics)} & -- \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ])

    return "\n".join(lines)


def generate_summary_json(metrics: list[TaskMetrics], runs: list[dict]) -> dict:
    """Generate comprehensive JSON summary for all paper metrics."""
    tni_data = to_json(metrics)

    # Per-category stats
    cat_metrics: dict[str, list[TaskMetrics]] = defaultdict(list)
    for m in metrics:
        cat_metrics[_task_category(m.task_id)].append(m)

    per_category = {}
    for cat, ms in sorted(cat_metrics.items()):
        n = len(ms)
        per_category[cat] = {
            "count": n,
            "avg_oracle": round(sum(m.oracle_partial for m in ms) / n, 4),
            "avg_restricted": round(sum(m.restricted_partial for m in ms) / n, 4),
            "avg_full": round(sum(m.team_partial for m in ms) / n, 4),
            "avg_uplift": round(sum(m.team_uplift for m in ms) / n, 4),
            "team_wins": sum(1 for m in ms if m.team_partial > m.oracle_partial + 0.01),
        }

    # Key findings
    team_wins = [m for m in metrics if m.team_partial > m.oracle_partial + 0.01]
    team_loses = [m for m in metrics if m.team_partial < m.oracle_partial - 0.1]
    valid_tni = [m for m in metrics if not math.isnan(m.tni) and m.necessity_gap > 0.05]

    findings = {
        "total_tasks_evaluated": len(metrics),
        "total_runs": len(runs),
        "team_outperforms_oracle": len(team_wins),
        "team_outperforms_oracle_tasks": [m.task_id for m in team_wins],
        "oracle_outperforms_team": len(team_loses),
        "valid_tni_tasks": len(valid_tni),
        "avg_tni": round(sum(m.tni for m in valid_tni) / len(valid_tni), 4) if valid_tni else None,
        "avg_team_uplift": round(sum(m.team_uplift for m in metrics) / len(metrics), 4),
        "avg_planning_value": round(
            sum(m.planning_value for m in metrics if not math.isnan(m.planning_value))
            / max(1, sum(1 for m in metrics if not math.isnan(m.planning_value))),
            4,
        ),
        "avg_verification_value": round(
            sum(m.verification_value for m in metrics if not math.isnan(m.verification_value))
            / max(1, sum(1 for m in metrics if not math.isnan(m.verification_value))),
            4,
        ),
    }

    return {
        "per_task": tni_data["tasks"],
        "aggregate": tni_data["aggregate"],
        "per_category": per_category,
        "findings": findings,
    }


def generate_statistical_analysis(metrics: list[TaskMetrics], runs: list[dict]) -> str:
    """Generate statistical analysis text for the paper results section."""
    from harness.statistics import bootstrap_ci

    lines = []
    lines.append("=" * 70)
    lines.append("STATISTICAL ANALYSIS — TeamBench Ablation Study")
    lines.append("=" * 70)

    n = len(metrics)
    lines.append(f"\nSample: {n} tasks, {len(runs)} total runs")
    lines.append(f"Model: Gemini 2.5 Flash")

    # Per-condition average partial scores
    cond_partials: dict[str, list[float]] = defaultdict(list)
    for run in runs:
        cond_partials[run["condition"]].append(
            run.get("partial_score", 1.0 if run.get("pass") else 0.0)
        )

    lines.append(f"\n--- Condition-Level Partial Scores ---")
    for cond in ["oracle", "restricted", "full", "team_no_plan", "team_no_verify"]:
        vals = cond_partials.get(cond, [])
        if vals:
            avg = sum(vals) / len(vals)
            # Bootstrap CI on partial scores (convert to binary above/below median for CI)
            binary = [v > 0.5 for v in vals]
            mean, lo, hi = bootstrap_ci(binary, n_bootstrap=10000, alpha=0.05)
            lines.append(f"  {cond:20s}: avg={avg:.3f}  n={len(vals):3d}  "
                         f"pass_rate={mean:.3f} [{lo:.3f}, {hi:.3f}]")

    # Team uplift distribution across tasks
    uplifts = [m.team_uplift for m in metrics]
    avg_uplift = sum(uplifts) / max(1, len(uplifts))
    positive = sum(1 for u in uplifts if u > 0.01)
    negative = sum(1 for u in uplifts if u < -0.01)
    neutral = n - positive - negative

    lines.append(f"\n--- Team Uplift Analysis ---")
    lines.append(f"  Avg uplift (Full - Restricted): {avg_uplift:+.3f}")
    lines.append(f"  Positive uplift: {positive}/{n} ({positive/max(1,n):.0%})")
    lines.append(f"  Negative uplift: {negative}/{n} ({negative/max(1,n):.0%})")
    lines.append(f"  Neutral:         {neutral}/{n} ({neutral/max(1,n):.0%})")

    # Planning value distribution
    pvs = [m.planning_value for m in metrics if not math.isnan(m.planning_value)]
    if pvs:
        avg_pv = sum(pvs) / len(pvs)
        pv_positive = sum(1 for v in pvs if v > 0.01)
        lines.append(f"\n--- Planning Value ---")
        lines.append(f"  Avg Planning Value: {avg_pv:+.3f}")
        lines.append(f"  Positive: {pv_positive}/{len(pvs)} ({pv_positive/max(1,len(pvs)):.0%})")
        lines.append(f"  Max: {max(pvs):+.3f} ({[m.task_id for m in metrics if not math.isnan(m.planning_value) and m.planning_value == max(pvs)][0] if pvs else 'N/A'})")

    # Verification value distribution
    vvs = [m.verification_value for m in metrics if not math.isnan(m.verification_value)]
    if vvs:
        avg_vv = sum(vvs) / len(vvs)
        vv_positive = sum(1 for v in vvs if v > 0.01)
        lines.append(f"\n--- Verification Value ---")
        lines.append(f"  Avg Verification Value: {avg_vv:+.3f}")
        lines.append(f"  Positive: {vv_positive}/{len(vvs)} ({vv_positive/max(1,len(vvs)):.0%})")

    # Team > Oracle analysis (key finding for paper)
    team_wins = [(m.task_id, m.team_partial - m.oracle_partial)
                 for m in metrics if m.team_partial > m.oracle_partial + 0.01]
    lines.append(f"\n--- Team > Oracle (Key Finding) ---")
    lines.append(f"  Tasks where team outperforms oracle: {len(team_wins)}/{n}")
    for tid, delta in sorted(team_wins, key=lambda x: -x[1]):
        lines.append(f"    {tid:25s} +{delta:.2f}")
    lines.append(f"\n  Interpretation: On {len(team_wins)}/{n} tasks, the 3-role team with")
    lines.append(f"  remediation loops outperforms a single oracle agent with full access.")
    lines.append(f"  This demonstrates that role separation and verification-driven")
    lines.append(f"  iteration provide complementary value beyond raw capability.")

    # Required sample size for future studies
    from harness.statistics import required_sample_size
    n_needed = required_sample_size(effect_size=0.10, alpha=0.05, power=0.8)
    lines.append(f"\n--- Sample Size Guidance ---")
    lines.append(f"  To detect 10pp difference at p<0.05 with 80% power: n={n_needed} per condition")
    lines.append(f"  Current: {n} tasks x 1 seed = {n} instances per condition")
    lines.append(f"  Recommended: {n} tasks x 3 seeds = {n*3} instances per condition")

    lines.append(f"\n{'='*70}")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate TeamBench paper tables")
    ap.add_argument(
        "--ablation", nargs="+", required=True,
        help="Ablation result JSON files to merge",
    )
    ap.add_argument(
        "--output-dir", default="shared/paper",
        help="Directory for output files",
    )
    args = ap.parse_args()

    # Merge all ablation files
    runs = merge_ablation_files(args.ablation)
    metrics = runs_to_task_metrics(runs)

    print(f"Merged {len(runs)} runs across {len(metrics)} tasks")

    os.makedirs(args.output_dir, exist_ok=True)

    # Generate tables
    table2 = generate_table2(metrics)
    table3 = generate_table3(metrics)
    table4 = generate_table4(metrics)
    summary = generate_summary_json(metrics, runs)

    # Write outputs
    for name, content in [
        ("table2_ablation.tex", table2),
        ("table3_category.tex", table3),
        ("table4_components.tex", table4),
    ]:
        path = os.path.join(args.output_dir, name)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"  {path}")

    summary_path = os.path.join(args.output_dir, "ablation_summary.json")
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)
    print(f"  {summary_path}")

    # Statistical analysis
    analysis = generate_statistical_analysis(metrics, runs)
    analysis_path = os.path.join(args.output_dir, "statistical_analysis.txt")
    with open(analysis_path, "w", encoding="utf-8") as f:
        f.write(analysis)
    print(f"  {analysis_path}")

    # Print key findings
    print(f"\n{'='*60}")
    print(f"KEY FINDINGS ({len(metrics)} tasks, {len(runs)} runs)")
    print(f"{'='*60}")
    f = summary["findings"]
    print(f"  Team > Oracle:     {f['team_outperforms_oracle']}/{f['total_tasks_evaluated']} tasks")
    if f["team_outperforms_oracle_tasks"]:
        print(f"    Tasks: {', '.join(f['team_outperforms_oracle_tasks'])}")
    print(f"  Avg TNI:           {f['avg_tni']}" if f["avg_tni"] else "  Avg TNI: N/A")
    print(f"  Avg Team Uplift:   {f['avg_team_uplift']:+.4f}")
    print(f"  Avg Planning Val:  {f['avg_planning_value']:+.4f}")
    print(f"  Avg Verif. Val:    {f['avg_verification_value']:+.4f}")


if __name__ == "__main__":
    main()
