#!/usr/bin/env bash
set -o pipefail
WORKSPACE="$1"
REPORTS="$2"
SUBMISSION="$3"
TASK_DIR="$4"

mkdir -p "$REPORTS"

CHECKS=0; PASSED=0; FAILURES=""
check() {
  CHECKS=$((CHECKS + 1))
  if eval "$1" 2>/dev/null; then
    PASSED=$((PASSED + 1))
  else
    FAILURES="${FAILURES:+${FAILURES},}$2"
  fi
}

cd "$WORKSPACE"

# ── Load expected values from grader ground truth ────────────────────────────
EXPECTED="$REPORTS/expected.json"

# 1. No hardcoded secret values in any Python source file
#    Patterns cover all four secret groups generated by the generator.
check "python3 -c \"
import os, re

bad_patterns = [
    # Group 0 secrets
    'Sup3rS3cr3tDbPass',
    'prod_admin',
    'pk_live_abc123XYZ456def789',
    'my-super-secret-jwt-key-do-not-share',
    'EmailP@ssw0rd2024',
    # Group 1 secrets
    'Pr0dDB\\\$ecret99',
    'prod-db-01.internal',
    'AES256-key-abcdef1234567890abcdef12',
    'whsec_live_XYZ789abc012def345ghi',
    'wJalrXUtnFEMI/K7MDENG/bPxRfiCY',
    # Group 2 secrets
    'pgS3cur3Pass',
    'oauth_secret_abc123def456ghi789',
    'BEGIN PRIVATE KEY',
    'mon_tok_xyz9876abc5432def',
    # Group 3 secrets
    'Mysql\\\$ecret!Prod',
    'Redis@Auth2024',
    'sk_live_51NqBkL2eZvKYlo2CXYZabc123',
    'ac1234567890abcdef1234567890abcd',
    'fernet-key-base64-abc123XYZ456def789',
]

found = []
for fname in os.listdir('.'):
    if not fname.endswith('.py'):
        continue
    with open(fname) as f:
        code = f.read()
    for pat in bad_patterns:
        if pat in code:
            found.append(f'{fname}: {pat!r}')

assert len(found) == 0, f'Hardcoded secrets found: {found}'
print('NO_HARDCODED_SECRETS')
\"" "hardcoded_secrets_present"

# 2. vault_client.py exists and defines the expected client class
check "python3 -c \"
import ast, json, os

# Read expected vault client class from expected.json
expected = json.load(open('$EXPECTED'))
cls_name = expected['vault_client_class']

with open('vault_client.py') as f:
    code = f.read()

tree = ast.parse(code)
class_names = [node.name for node in ast.walk(tree) if isinstance(node, ast.ClassDef)]
assert cls_name in class_names, f'Expected class {cls_name} not found in vault_client.py. Found: {class_names}'
print('VAULT_CLIENT_CLASS_DEFINED')
\"" "vault_client_class_missing"

# 3. Vault client has the required secret retrieval method
check "python3 -c \"
import ast, json

expected = json.load(open('$EXPECTED'))
cls_name = expected['vault_client_class']

with open('vault_client.py') as f:
    code = f.read()

tree = ast.parse(code)
methods_found = []
for node in ast.walk(tree):
    if isinstance(node, ast.ClassDef) and node.name == cls_name:
        for item in node.body:
            if isinstance(item, ast.FunctionDef):
                methods_found.append(item.name)

required_methods = {'get_secret', 'read', 'fetch'}
has_method = bool(required_methods & set(methods_found))
assert has_method, f'{cls_name} missing a secret retrieval method. Found: {methods_found}'
print('VAULT_CLIENT_METHOD_OK')
\"" "vault_client_method_missing"

# 4. Entrypoint imports vault_client (vault is initialized at startup)
check "python3 -c \"
import json, ast, os

expected = json.load(open('$EXPECTED'))
svc_type = expected['service_type']

# Map service type to entrypoint filename
entrypoints = {
    'web_app': 'server.py',
    'microservice': 'main.py',
    'worker': 'worker.py',
    'scheduler': 'scheduler.py',
}
entrypoint = entrypoints.get(svc_type, 'server.py')

assert os.path.exists(entrypoint), f'Entrypoint {entrypoint} not found'
with open(entrypoint) as f:
    code = f.read()

# Must import from vault_client
has_vault_import = 'vault_client' in code or 'from vault_client' in code
assert has_vault_import, f'{entrypoint} does not import vault_client'
print('VAULT_IMPORTED_IN_ENTRYPOINT')
\"" "vault_not_imported_in_entrypoint"

# 5. Phase 1 secrets (DB credentials) are referenced before Phase 2 secrets
#    in the entrypoint — rotation order check
check "python3 -c \"
import json, os

expected = json.load(open('$EXPECTED'))
svc_type = expected['service_type']
rotation = expected['rotation_order']

entrypoints = {
    'web_app': 'server.py',
    'microservice': 'main.py',
    'worker': 'worker.py',
    'scheduler': 'scheduler.py',
}
entrypoint = entrypoints.get(svc_type, 'server.py')

if not os.path.exists(entrypoint):
    print('ENTRYPOINT_NOT_FOUND_SKIP')
    exit(0)

with open(entrypoint) as f:
    code = f.read()

phase1 = rotation.get('phase_1', [])
phase2 = rotation.get('phase_2', [])

if not phase1 or not phase2:
    print('ROTATION_ORDER_OK_NO_PHASES')
    exit(0)

# Find positions of first phase1 and first phase2 references
# Accept either the variable name or any substring of the vault path
def find_first_pos(code, names):
    positions = []
    for name in names:
        idx = code.find(name)
        if idx >= 0:
            positions.append(idx)
    return min(positions) if positions else -1

p1_pos = find_first_pos(code, phase1)
p2_pos = find_first_pos(code, phase2)

if p1_pos < 0 and p2_pos < 0:
    # Neither phase referenced by name — check for 'database' before 'api'
    db_pos = code.lower().find('database')
    api_pos = code.lower().find('api_key')
    if db_pos >= 0 and api_pos >= 0:
        assert db_pos < api_pos, 'Database credentials loaded after API keys (wrong rotation order)'
    print('ROTATION_ORDER_OK_BY_COMMENT')
    exit(0)

if p1_pos >= 0 and p2_pos >= 0:
    assert p1_pos < p2_pos, f'Phase 1 secrets appear after Phase 2 secrets in {entrypoint}'

print('ROTATION_ORDER_OK')
\"" "wrong_rotation_order"

# 6. All secret-bearing files have no hardcoded assignment patterns
#    (catches cases where the value was replaced but the var still assigned inline)
check "python3 -c \"
import json, ast, os

expected = json.load(open('$EXPECTED'))
secret_files = expected.get('secret_files', [])

dangerous_literal_patterns = [
    'Sup3rS3cr3t', 'Pr0dDB', 'pgS3cur3', 'Mysql\$ecret',
    'pk_live_', 'sk_live_', 'whsec_live_', 'oauth_secret_',
    'AES256-key', 'fernet-key', 'EmailP@ssw0rd', 'Redis@Auth',
]

for fname in secret_files:
    if not os.path.exists(fname):
        continue
    with open(fname) as f:
        code = f.read()
    for pat in dangerous_literal_patterns:
        assert pat not in code, f'{fname} still contains hardcoded pattern: {pat!r}'

print('SECRET_FILES_CLEAN')
\"" "secret_files_contain_hardcoded"

# 7. All Python files are syntactically valid
check "python3 -c \"
import py_compile, os

errors = []
for root, dirs, files in os.walk('.'):
    # Skip hidden dirs and venv
    dirs[:] = [d for d in dirs if not d.startswith('.') and d not in ('venv', '__pycache__')]
    for fname in files:
        if fname.endswith('.py'):
            path = os.path.join(root, fname)
            try:
                py_compile.compile(path, doraise=True)
            except py_compile.PyCompileError as e:
                errors.append(str(e))

assert len(errors) == 0, f'Syntax errors: {errors}'
print('SYNTAX_OK')
\"" "syntax_error"

# 8. vault_client.py is syntactically valid and importable (no runtime errors at import)
check "python3 -c \"
import py_compile
py_compile.compile('vault_client.py', doraise=True)

# Also verify the module doesn't crash on import
import importlib.util, sys
spec = importlib.util.spec_from_file_location('vault_client', 'vault_client.py')
mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)
print('VAULT_CLIENT_IMPORTABLE')
\"" "vault_client_import_error"

# 9. config.py exists and does not contain secret values
check "python3 -c \"
import os
assert os.path.exists('config.py'), 'config.py not found'

with open('config.py') as f:
    code = f.read()

# config.py should reference vault config (prefix/path/endpoint/token vars)
has_vault_cfg = any(kw in code for kw in [
    'VAULT_PREFIX', 'VAULT_PATH', 'VAULT_ENDPOINT', 'VAULT_TOKEN',
    'vault', 'Vault', 'VAULT',
])
assert has_vault_cfg, 'config.py has no vault configuration'

# Must not contain any of the hardcoded secret values
bad = ['Sup3rS3cr3t', 'Pr0dDB', 'pgS3cur3', 'pk_live_', 'sk_live_', 'oauth_secret_', 'AES256']
for pat in bad:
    assert pat not in code, f'Hardcoded secret pattern in config.py: {pat!r}'
print('CONFIG_OK')
\"" "config_missing_or_contains_secrets"

# 10. Tests exist and contain meaningful assertions
check "python3 -c \"
import os
assert os.path.exists('tests/test_secrets.py'), 'tests/test_secrets.py not found'

with open('tests/test_secrets.py') as f:
    code = f.read()

assert 'def test_' in code, 'No test functions found in tests/test_secrets.py'
assert 'assert' in code, 'No assertions found in test file'
print('TESTS_FILE_OK')
\"" "tests_file_missing_or_empty"

# 11. pytest passes on test_secrets.py (best-effort; skip if pytest not installed)
check "python3 -m pytest tests/test_secrets.py -x -q --tb=short 2>&1 | tail -5 | grep -E '(passed|no tests ran|PASSED)'" "tests_failed"

# 12. No new dangerous patterns introduced
check "python3 -c \"
import os

bad_patterns = ['eval(', 'exec(', '__import__(', 'compile(', 'pickle.loads(']
violations = []

for root, dirs, files in os.walk('.'):
    dirs[:] = [d for d in dirs if not d.startswith('.') and d not in ('venv', '__pycache__')]
    for fname in files:
        if not fname.endswith('.py'):
            continue
        path = os.path.join(root, fname)
        with open(path) as f:
            code = f.read()
        for pat in bad_patterns:
            if pat in code:
                violations.append(f'{path}: {pat}')

assert len(violations) == 0, f'Dangerous patterns introduced: {violations}'
print('NO_DANGEROUS_PATTERNS')
\"" "dangerous_pattern_introduced"

# 13. Attestation
check "python3 -c \"
import json, sys
att = json.load(open(sys.argv[1]))
assert att.get('verdict') == 'pass'
\" '$SUBMISSION/attestation.json'" "bad_attestation"

PARTIAL=$(python3 -c "print(round($PASSED/max(1,$CHECKS), 2))")
if [ "$PASSED" -eq "$CHECKS" ]; then SUCCESS=1; PASS=true; else SUCCESS=0; PASS=false; fi
FM=$(python3 -c "import json; print(json.dumps([x for x in '${FAILURES}'.split(',') if x]))")

cat > "$REPORTS/score.json" <<JSON
{
  "pass": $PASS,
  "primary": {"success": $SUCCESS},
  "secondary": {"checks_passed": $PASSED, "checks_total": $CHECKS, "partial_score": $PARTIAL},
  "failure_modes": $FM
}
JSON
